#!/usr/bin/env python3
"""Generate src/bm25_sb_wordclass.c: the word-class bitmap for the HIGH half
(0x80-0xFF) of every single-byte PostgreSQL server encoding (issue #295).

Role in the system. bm25_is_word_byte (src/bm25_analyzer.c) is the one place
the extension decides "is this byte part of a word". In a single-byte server
encoding a high byte is a whole character, so the answer has to come from the
ENCODING: which character the byte is, and whether that character is a letter
or digit. This script computes that answer once, offline, and writes it out as
fixed C data, so the analyzer's run splitting stays a pure function of the
database encoding -- which the analyzer fingerprint already records.

Why generated fixed data rather than a runtime lookup (ADR 0077's determinism
goal, kept):

  - Not LC_CTYPE. isalnum() under the locale is what ADR 0077 removed, because
    LC_CTYPE is not recorded anywhere the fingerprint can see.
  - Not pg_do_encoding_conversion. It resolves the conversion through
    pg_conversion, so a CREATE DEFAULT CONVERSION on search_path could change
    the answer -- an environment input the fingerprint does not record.
  - Not the server's pg_u_isalnum at run time. PostgreSQL's Unicode tables move
    with the major version (17: Unicode 15.1, 18: 16.0, 19: 17.0), so the same
    byte could change class across a pg_upgrade with nothing to detect it.
    Pinning the classification here removes that drift entirely: the table is
    a property of this extension's source, and changing it is an analyzer
    revision bump like any other output change.

Inputs, both from ONE pinned PostgreSQL source tree (--pg-source):

  - src/backend/utils/mb/Unicode/<enc>_to_utf8.map: the byte -> Unicode
    mapping PostgreSQL's own built-in conversions use. LATIN1 has no map file
    because its conversion is the identity (byte value == code point).
  - src/include/common/unicode_category_table.h: "word character" is exactly
    PostgreSQL's pg_u_isalnum(code, posix = false) -- the Alphabetic derived
    property, or general category Nd -- evaluated over this tree's tables.

Rules:
  - A byte whose character is Alphabetic or Nd is a word byte.
  - A byte with NO mapping in the encoding (e.g. WIN1251 0x98) is a separator.
  - A combining mark is a word byte only if Unicode calls it Alphabetic. Marks that
    are not stay separators, so decomposed text splits at them: WIN1258's combining
    accents (0xCC, 0xD2, 0xDE, 0xEC, 0xF2) and WIN874's tone and similar marks (0xE7
    to 0xEC, 0xEE). Not a regression: every high byte was a separator before
    revision 6. Recorded in docs/adr/0114.
  - SQL_ASCII is not tabled: it declares no character set, its high bytes are
    usually UTF-8 written through a database that does not check them, and the
    analyzer treats them as word bytes exactly as it does in a multibyte
    encoding (bm25_is_word_byte).

Usage:
  python3 ci/gen_sb_wordclass.py --pg-source ~/Documents/Dev/postgresql-18.6 \
      > src/bm25_sb_wordclass.c
  python3 ci/gen_sb_wordclass.py --pg-source ... --check src/bm25_sb_wordclass.c

The output is deliberately NOT regenerated by the build or by CI: a different
PostgreSQL source tree would silently produce a different (Unicode-version
dependent) table, which is precisely the drift this file exists to prevent.
Regenerate only on purpose, and bump BM25_ANALYZER_REVISION if the bytes move.
"""
import argparse
import os
import re
import sys

# Every single-byte SERVER encoding, by its pg_enc enum name, with the map file
# stem that PostgreSQL's utf8_and_iso8859 / utf8_and_win / utf8_and_cyrillic
# conversion procs pair it with. None = identity mapping (LATIN1). The enum
# order is PostgreSQL's (src/include/mb/pg_wchar.h); it is kept here only so
# the generated file reads in a stable order.
ENCODINGS = [
    ('PG_LATIN1', None),
    ('PG_LATIN2', 'iso8859_2'),
    ('PG_LATIN3', 'iso8859_3'),
    ('PG_LATIN4', 'iso8859_4'),
    ('PG_LATIN5', 'iso8859_9'),
    ('PG_LATIN6', 'iso8859_10'),
    ('PG_LATIN7', 'iso8859_13'),
    ('PG_LATIN8', 'iso8859_14'),
    ('PG_LATIN9', 'iso8859_15'),
    ('PG_LATIN10', 'iso8859_16'),
    ('PG_WIN1256', 'win1256'),
    ('PG_WIN1258', 'win1258'),
    ('PG_WIN866', 'win866'),
    ('PG_WIN874', 'win874'),
    ('PG_KOI8R', 'koi8r'),
    ('PG_WIN1251', 'win1251'),
    ('PG_WIN1252', 'win1252'),
    ('PG_ISO_8859_5', 'iso8859_5'),
    ('PG_ISO_8859_6', 'iso8859_6'),
    ('PG_ISO_8859_7', 'iso8859_7'),
    ('PG_ISO_8859_8', 'iso8859_8'),
    ('PG_WIN1250', 'win1250'),
    ('PG_WIN1253', 'win1253'),
    ('PG_WIN1254', 'win1254'),
    ('PG_WIN1255', 'win1255'),
    ('PG_WIN1257', 'win1257'),
    ('PG_KOI8U', 'koi8u'),
]


def read(path):
    with open(path, encoding='ascii') as f:
        return f.read()


def parse_ranges(src, name):
    """Return the (first, last) pairs of a pg_unicode_range / pg_category_range
    array named `name`, plus the category token for the latter."""
    m = re.search(r'\b' + name + r'\[\d+\]\s*=\s*\{(.*?)\n\};', src, re.S)
    if not m:
        sys.exit('cannot find %s in unicode_category_table.h' % name)
    out = []
    for e in re.finditer(r'\{\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*(?:,\s*(\w+))?\s*\}',
                         m.group(1)):
        out.append((int(e.group(1), 16), int(e.group(2), 16), e.group(3)))
    if not out:
        sys.exit('empty range table %s' % name)
    return out


def utf8_to_cp(v):
    """A map entry packs the character's UTF-8 bytes into a uint32, most
    significant byte first (0x00d082 is D0 82). Decode it to a code point."""
    bs = v.to_bytes(4, 'big').lstrip(b'\x00')
    return ord(bs.decode('utf-8'))


def parse_map(path, stem):
    """Byte -> code point (or None when unmapped) for 0x80..0xFF, read from the
    radix tree's 1-byte leaf exactly as pg_mb_radix_conv does."""
    src = read(path)
    tree = re.search(stem + r'_to_unicode_tree\s*=\s*\{(.*?)\};', src, re.S).group(1)
    fields = [int(x, 16) for x in re.findall(r'(0x[0-9a-fA-F]+)\s*,?\s*/\*', tree)]
    # Field order after the two table pointers: b1root, b1_lower, b1_upper, ...
    b1root, b1_lower, b1_upper = fields[0], fields[1], fields[2]
    body = re.search(stem + r'_to_unicode_tree_table\[\d+\]\s*=\s*\{(.*?)\n\};', src, re.S).group(1)
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)
    table = [int(x, 16) for x in re.findall(r'0x[0-9a-fA-F]+', body)]
    out = {}
    for b in range(0x80, 0x100):
        if b < b1_lower or b > b1_upper:
            out[b] = None
            continue
        v = table[b1root + b - b1_lower]
        out[b] = utf8_to_cp(v) if v else None
    return out


def make_isalnum(cat_src):
    alpha = parse_ranges(cat_src, 'unicode_alphabetic')
    cats = parse_ranges(cat_src, 'unicode_categories')

    def in_ranges(cp, ranges):
        return any(lo <= cp <= hi for lo, hi, _ in ranges)

    def isalnum(cp):
        if in_ranges(cp, alpha):
            return True
        for lo, hi, cat in cats:
            if lo <= cp <= hi:
                return cat == 'PG_U_DECIMAL_NUMBER'
        return False
    return isalnum


def generate(pg):
    uni = os.path.join(pg, 'src/backend/utils/mb/Unicode')
    cat_src = read(os.path.join(pg, 'src/include/common/unicode_category_table.h'))
    ver = re.search(r'PG_UNICODE_VERSION\s+"([^"]+)"',
                    read(os.path.join(pg, 'src/include/common/unicode_version.h'))).group(1)
    pgver = re.search(r"PACKAGE_VERSION='([^']+)'", read(os.path.join(pg, 'configure'))).group(1)
    isalnum = make_isalnum(cat_src)

    lines = []
    w = lines.append
    w('/* bm25_sb_wordclass.c -- GENERATED by ci/gen_sb_wordclass.py; do not edit by hand.')
    w(' *')
    w(' * Role in the system: the word-class table bm25_is_word_byte (bm25_analyzer.c) consults')
    w(' * for a HIGH byte (0x80-0xFF) in a single-byte server encoding, where such a byte is a')
    w(' * whole character (issue #295). One bit per byte: set = the character is a letter or')
    w(' * digit (a word byte), clear = a separator, including every byte the encoding leaves')
    w(' * unmapped. ASCII (0x00-0x7F) is not covered here; the analyzer classifies it itself.')
    w(' *')
    w(' * PINNED, deliberately: generated from PostgreSQL %s\'s conversion maps' % pgver)
    w(' * (src/backend/utils/mb/Unicode/<enc>_to_utf8.map; LATIN1 is the identity) and its')
    w(' * pg_u_isalnum classification (Alphabetic or Nd) at Unicode %s. Run splitting decides' % ver)
    w(' * document length and therefore every score, so it must not drift with the server\'s')
    w(' * own Unicode tables across a pg_upgrade. Any change to these bytes is an analyzer')
    w(' * output change: bump BM25_ANALYZER_REVISION with it. See the generator\'s docstring')
    w(' * for why neither LC_CTYPE nor a runtime conversion is used. */')
    w('')
    w('#include "postgres.h"')
    w('')
    w('#include "bm25.h"')
    w('#include "mb/pg_wchar.h"')
    w('')
    w('/* Bit (b - 0x80) & 7 of byte (b - 0x80) >> 3 is set when high byte b is a word byte. */')
    total = {}
    for enc, stem in ENCODINGS:
        if stem is None:
            m = {b: b for b in range(0x80, 0x100)}
        else:
            m = parse_map(os.path.join(uni, stem + '_to_utf8.map'), stem)
        bits = [0] * 16
        n = 0
        for b in range(0x80, 0x100):
            cp = m[b]
            if cp is not None and isalnum(cp):
                bits[(b - 0x80) >> 3] |= 1 << ((b - 0x80) & 7)
                n += 1
        unmapped = sum(1 for b in range(0x80, 0x100) if m[b] is None)
        total[enc] = n
        cname = 'sbwc_' + enc[3:].lower()
        w('static const uint8 %s[16] = {  /* %d word bytes, %d unmapped */' % (cname, n, unmapped))
        w('    ' + ', '.join('0x%02x' % x for x in bits[:8]) + ',')
        w('    ' + ', '.join('0x%02x' % x for x in bits[8:]))
        w('};')
    w('')
    w('/* Indexed by pg_enc. NULL for every encoding that is not a single-byte server')
    w(' * encoding (SQL_ASCII included -- see bm25_is_word_byte). pg_enc values are stable')
    w(' * across majors: they are stored in pg_database.encoding. */')
    w('static const uint8 *const sbwc_by_encoding[PG_KOI8U + 1] = {')
    for enc, _ in ENCODINGS:
        w('    [%s] = sbwc_%s,' % (enc, enc[3:].lower()))
    w('};')
    w('')
    w('/*')
    w(' * bm25_sb_wordclass -- the high-half bitmap for a single-byte server encoding, or')
    w(' * NULL when `encoding` has none (multibyte encodings, SQL_ASCII, client-only')
    w(' * encodings, or an out-of-range value).')
    w(' */')
    w('const uint8 *')
    w('bm25_sb_wordclass(int encoding)')
    w('{')
    w('    if (encoding < 0 || encoding >= (int) lengthof(sbwc_by_encoding))')
    w('        return NULL;')
    w('    return sbwc_by_encoding[encoding];')
    w('}')
    return '\n'.join(lines) + '\n'


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--pg-source', required=True, help='PostgreSQL source tree root')
    ap.add_argument('--check', metavar='FILE',
                    help='compare against FILE instead of printing; exit 1 on difference')
    a = ap.parse_args()
    out = generate(os.path.expanduser(a.pg_source))
    if a.check:
        if read(a.check) != out:
            print('%s differs from what --pg-source generates' % a.check, file=sys.stderr)
            return 1
        return 0
    sys.stdout.write(out)
    return 0


if __name__ == '__main__':
    sys.exit(main())
